spring.datasource.url=jdbc:postgresql://db.fqygmtajeugelxmycenl.supabase.co:5432/postgres

spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD:kronsoft-medistock}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=${JWT_SECRET:0_Cheie_Super_Secreta_Krontech_Pentru_Test_Local_2026!!!}