spring.datasource.url=jdbc:postgresql://db.xesdohgirbifrtvhdbqd.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=Parolaputernica

# Hibernate - creeaz? automat tabelele pe baza claselor Java
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect